---
title: "Main project"
author: "Galina Chernaya, Iuliia Matvienko, Olga Serebryakova, Polina Burmakina"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)
library(readxl)
library(gtsummary)
library(stringr)
library(janitor)
library(openxlsx2)
library(tidyr)
library(lubridate)
library(ggplot2)
library(survival)
library(ggsurvfit)
library(tidycmprsk)
library(psych)
library(DT)
library(dbplyr)
library(labelled)
```

## 1.Загрузка данных

```{r}

df_meta <- read.csv("names.csv", sep = ",", header = TRUE, fileEncoding = "UTF-8")


df <- openxlsx2::read_xlsx("Donor Immune cells (1).xlsx", sheet = 1)  

df <- as_tibble(df, .name_repair = "minimal")

df <- set_names(df, df_meta$cleaned_names)

df <- df %>%
  mutate(across(where(is.character), ~ gsub("_", " ", .)))

# Исключаем 2 случая с диагнозом мукополисахаридоз и остеопетроз

df <- df %>% filter(!(str_detect(gruppa_diagnozov_po_voz_a_zgem, "Врожденные / наследственные заболевания")))
```

## 2.Подготовка данных к анализу

### Переменные из группы 1:


```{r} 
Donor <- df[, c(1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 105, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121)]

#Предобработка данных

Donor$gruppa_krovi_donora_ptkm_pred_tk_me_tk_ma <- case_when(
  Donor$gruppa_krovi_donora_ptkm_pred_tk_me_tk_ma == '0 I' ~ '0 I',
  Donor$gruppa_krovi_donora_ptkm_pred_tk_me_tk_ma == 'A II' ~ 'A II',
  Donor$gruppa_krovi_donora_ptkm_pred_tk_me_tk_ma == 'A2 II' ~ 'A II',
  Donor$gruppa_krovi_donora_ptkm_pred_tk_me_tk_ma == 'B III' ~ 'B III',
  Donor$gruppa_krovi_donora_ptkm_pred_tk_me_tk_ma == 'AB IV' ~ 'AB IV'
)
```

```{r}
Donor <- add_column(Donor, male = '', .after = 22)

Donor <- Donor %>%
  mutate(
    male <- case_when(harakteristika_donora_ptkm == 'мужчина' ~ '1',
                               harakteristika_donora_ptkm == 'отец мужчина' ~ '1',  
                               harakteristika_donora_ptkm == 'отец' ~ '1',
                               harakteristika_donora_ptkm == 'брат' ~ '1',
                               harakteristika_donora_ptkm == 'сын' ~ '1',
                               harakteristika_donora_ptkm == 'женщина' ~ '0',
                               harakteristika_donora_ptkm == 'мать' ~ '0',
                               harakteristika_donora_ptkm == 'сестра' ~ '0',
                               harakteristika_donora_ptkm == 'дочь' ~ '0'))

Donor$male <- Donor$`... <- NULL`
Donor <- Donor[,-37]

Donor$male <- as.integer(Donor$male)
```

```{r}
Donor <- add_column(Donor, relative = '', .after = 24)

Donor <- Donor %>%
  mutate(
    relative <- if_else(harakteristika_donora_ptkm == 'мужчина'|harakteristika_donora_ptkm == 'женщина', "0", "1"))

Donor$relative <- Donor$`... <- NULL` 
Donor <- Donor[,-38]

Donor$relative <- as.integer(Donor$relative)
```

```{r}
Donor$beremennosti_pred_tk_me <- ifelse(Donor$beremennosti_pred_tk_me == 'нет данных', NA, Donor$beremennosti_pred_tk_me)
```

```{r}
Donor$donor_vozrast_na_moment_tkm_pred_tk_me_ptkm <- as.integer(stringr::str_extract(Donor$donor_vozrast_na_moment_tkm_pred_tk_me_ptkm, "\\d+"))

```

```{r}
Donor$virusy_donora_cmv_pred_tk_me <- case_when(
    grepl("IgG\\(\\+\\)", Donor$virusy_donora_cmv_pred_tk_me) ~ "IgG(+)",
    !is.na(Donor$virusy_donora_cmv_pred_tk_me) ~ "IgG(-)",
    .default = NA_character_
)
Donor$virusy_donora_ebv_pred_tk_me <- case_when(
    grepl("IgG\\(\\+\\)", Donor$virusy_donora_ebv_pred_tk_me) ~ "IgG(+)",
    !is.na(Donor$virusy_donora_ebv_pred_tk_me) ~ "IgG(-)",
    .default = NA_character_
)
Donor$virusy_donora_toxoplassmosis_pred_tk_me <- case_when(
    grepl("IgG\\(\\+\\)", Donor$virusy_donora_toxoplassmosis_pred_tk_me) ~ "IgG(+)",
    !is.na(Donor$virusy_donora_toxoplassmosis_pred_tk_me) ~ "IgG(-)",
    .default = NA_character_
)
Donor$virusy_donora_hsv_1_2_pred_tk_me <- case_when(
    grepl("IgG\\(\\+\\)", Donor$virusy_donora_hsv_1_2_pred_tk_me) ~ "IgG(+)",
    !is.na(Donor$virusy_donora_hsv_1_2_pred_tk_me) ~ "IgG(-)",
    .default = NA_character_
)

Donor <- Donor[,-37]
```

```{r}
Donor <- Donor %>% mutate(
    gruppa_krovi_donora_ptkm_pred_tk_me_tk_ma = factor(gruppa_krovi_donora_ptkm_pred_tk_me_tk_ma), rezus_faktor_donora_ptkm_pred_tk_me_tk_ma = factor(rezus_faktor_donora_ptkm_pred_tk_me_tk_ma),
fenotip_eritrocitov_donora_ptkm_pred_tk_me_tk_ma = factor(fenotip_eritrocitov_donora_ptkm_pred_tk_me_tk_ma),
male = as.integer(male),
harakteristika_donora_ptkm = factor(harakteristika_donora_ptkm)
)

Donor$donor_ves_pred_tkme_ptkm <- str_replace(string = Donor$donor_ves_pred_tkme_ptkm,pattern = "[,]",replacement = ".")

Donor <- Donor %>% mutate(
  beremennosti_pred_tk_me = as.numeric(beremennosti_pred_tk_me),
  donor_vozrast_na_moment_tkm_pred_tk_me_ptkm = as.numeric(donor_vozrast_na_moment_tkm_pred_tk_me_ptkm),
  donor_rost_sm_pred_tk_me_ptkm = as.numeric(donor_rost_sm_pred_tk_me_ptkm),
  donor_ves_pred_tkme_ptkm = as.numeric(donor_ves_pred_tkme_ptkm)
)
```



### Переменные из группы 2:

```{r}
group2 <- df_meta %>% filter(Analysis_group == 2) %>% 
                      select(cleaned_names) %>% pull()


all_group2 <- df %>% select(all_of(group2)) 
```

```{r}
# Уберем лишние и неудобные переменные

all_group2 <- all_group2 %>%
  mutate(
    intratekalnoe_vvedenie = ifelse(grepl("^да", intratekal_noe_vvedenie_preparatov_da_net_data_preparaty_dozy_pred_tk_me), "да", ifelse(grepl("^нет", intratekal_noe_vvedenie_preparatov_da_net_data_preparaty_dozy_pred_tk_me), "нет", NA)),
    date_intratekalnoe_vvedenie = str_extract(intratekal_noe_vvedenie_preparatov_da_net_data_preparaty_dozy_pred_tk_me, "\\d{2}\\.\\d{2}\\.\\d{4}") %>% str_trim()) 


cleaned_group2 <- all_group2 %>% 
  select( -voz_klassifikacia_a_zgem, -gruppa_diagnozov_po_voz_a_zgem, # подробные диагнозы
          -diagnoz_diag_stac, -diagnoz_ico3_who_2016,
          -ves_pacienta,
          -s_tela_fakticeskaa_pred_tk_me,
          -restadirovanie_na_moment_tkm_mob_pred_tk_me,  
          -restadirovanie_na_moment_tkm_utocnenia_pred_tk_me,
          -restadirovanie_na_moment_tkm_dopolnenia_pred_tk_me,  
          -virusy_pacienta_hv6_pred_tk_me,
          -virusy_pacienta_f_50_pred_tk_me,
          -virusy_pacienta_hcv_pred_tk_me,
          -virusy_pacienta_hbv_pred_tk_me,
          -data_predydusej_tkm_tk_ma,  
          -vid_predydusej_tkm_tk_ma,
          -infekcionnye_osloznenia,
          -istocnik_predydusej_tkm_tk_ma,
          -pokazania_k_povtornoj_tkm_pred_tk_me,  
          -intratekal_noe_vvedenie_preparatov_da_net_data_preparaty_dozy_pred_tk_me,
          -date_intratekalnoe_vvedenie
          )
ncol(cleaned_group2)

```

```{r warning=FALSE}
## Типы данных
cleaned_types <- cleaned_group2 %>% mutate(across(c(pacient,
                                             d_z,
                                             pol,
                                             obsee_kolicestvo_tkm,
                                             vozrastnaa_gruppa,
                                             dannoe_zabolevanie_pervicnoe_da_net_a_zgem,
                                             gruppa_krovi_pred_tk_me,
                                             rezus_faktor_pred_tk_me,
                                             fenotip_eritrocitov_pred_tk_me,
                                             zaklucenie_norma_izbytocnaa_massa_tela,
                                             gruppa_pred_tk_me,
                                             vozrastnaa_gruppa
                                             ),~ as.factor(.x))) %>%
  
  mutate(indeks_massy_tela = gsub(",",".", indeks_massy_tela)) %>%
  mutate(across(c(klirens_kreatinina_pred_tk_me,
                  karnovskij_pered_tkm_pred_tk_me,
                  massa_tela_na_moment_tkm_ptkm,
                  indeks_massy_tela,
                  uroven_ferritina_pred_tk_me), ~ as.numeric(.x)))

```

```{r}
## Упорядочим простые столбцы, заполненим понятные пропуски
simplier <- cleaned_types %>%
  mutate(
   vozrastnaa_gruppa = case_when(
  vozrast_polnyh_let_na_moment_tkm < 18  ~ "< 18",
  vozrast_polnyh_let_na_moment_tkm >= 18 & vozrast_polnyh_let_na_moment_tkm < 50 ~ "18-50",
  vozrast_polnyh_let_na_moment_tkm >= 50 ~ "50+" ),
    dannoe_zabolevanie_pervicnoe_da_net_a_zgem = gsub("вторичное", "нет", dannoe_zabolevanie_pervicnoe_da_net_a_zgem),
    gruppa_pred_tk_me = gsub("высокого риска", "Standart", gruppa_pred_tk_me),
    gruppa_pred_tk_me = gsub("высокая группа риска", "Standart", gruppa_pred_tk_me),
  karnovskij_pered_tkm_pred_tk_me = case_when( karnovskij_pered_tkm_pred_tk_me < 80 ~ "менее 80",
                                               karnovskij_pered_tkm_pred_tk_me >= 80 ~ "80+"))
    
simplier$vozrastnaa_gruppa <- as.factor(simplier$vozrastnaa_gruppa)

# выражение из имт массы 
nan_weight <- function( indeks_massy_tela, rost_na_moment_tkm_pred_tk_me) {
  weight <- indeks_massy_tela * (rost_na_moment_tkm_pred_tk_me/100)^2
  return(weight)
}

# заполним пропуски
simplier$massa_tela_na_moment_tkm_ptkm[is.na(simplier$massa_tela_na_moment_tkm_ptkm)] <- nan_weight(simplier$indeks_massy_tela[is.na(simplier$massa_tela_na_moment_tkm_ptkm)], simplier$rost_na_moment_tkm_pred_tk_me[is.na(simplier$massa_tela_na_moment_tkm_ptkm)]) 

# Округлим кое-где
simplier <- simplier %>% 
  mutate_at(c("massa_tela_na_moment_tkm_ptkm", "klirens_kreatinina_pred_tk_me","rost_na_moment_tkm_pred_tk_me","uroven_ferritina_pred_tk_me",
              "serdecnyj_vybros_pred_tk_me", "indeks_massy_tela"), ~round(., 0))

# дополнили очевидные NA по информации из соседних столбцов
levels(simplier$d_z) <- c(levels(simplier$d_z), "OMЛ")

simplier$d_z[19] <- "OMЛ"
simplier$d_z[29] <- "ЮММЛ"
simplier$d_z[30] <- "ОЛЛ"
simplier$d_z[33] <- "ОЛЛ"

# немножко унифицировали рестадирование

simplier$restadirovanie_na_moment_tkm_stadia_pred_tk_me[93] <- NA
simplier$restadirovanie_na_moment_tkm_stadia_pred_tk_me[69] <- NA
simplier$restadirovanie_na_moment_tkm_stadia_pred_tk_me[62] <- NA
simplier$restadirovanie_na_moment_tkm_stadia_pred_tk_me[59] <- NA
simplier$restadirovanie_na_moment_tkm_stadia_pred_tk_me[15] <- NA
simplier$restadirovanie_na_moment_tkm_stadia_pred_tk_me[61] <- NA

patterns_to_remissiya <- c('хроническая фаза','трансфрмация в ОМЛ, ремиссия','DIPSS 2-3, фиброзно-склеротическая стадия', 'РАИБ 2', 'DIPSSplus промежуточный-2 риск', 'РАИБ-2, очень высокий риск IPSS-R','РАИБ1, IPSS-R', 'стадия IIIB', 'стадия IIIB, ремиссия')
patterns_to_recidiv <- c('бластный криз', 'прогрессия', 'прогрессия в ОМЛ', 'рецидив, циторедукция')
new_values <- c('ремиссия', 'рецидив')

# Заменяем значения в столбце в зависимости от паттерна
simplier <- simplier %>%
  mutate(restadirovanie_na_moment_tkm_stadia_pred_tk_me = case_when(
    str_detect(restadirovanie_na_moment_tkm_stadia_pred_tk_me, paste(patterns_to_recidiv, collapse = '|')) ~ new_values[2],
    str_detect(restadirovanie_na_moment_tkm_stadia_pred_tk_me, paste(patterns_to_remissiya, collapse = '|')) ~ new_values[1],
    TRUE ~ restadirovanie_na_moment_tkm_stadia_pred_tk_me
  ))

simplier <- simplier %>%
  mutate_at(vars(starts_with("virusy")), ~ifelse(grepl("IgG\\(\\+\\)", .), "IgG(+)",
                                                   ifelse(grepl("IgG\\(\\-\\)", .), "IgG(-)", NA))) 
 
simplier$gruppa_krovi_pred_tk_me <- gsub("_", " ", simplier$gruppa_krovi_pred_tk_me)
simplier$data_diagnoza_az_gem[68] <- NA
simplier$restadirovanie_na_moment_tkm_data_pred_tk_me[68] <- NA

simplier$pol <- gsub("Женский", "0",simplier$pol ) %>% as.factor
simplier$pol <- gsub("Мужской", "1", simplier$pol) %>% as.factor


# дочистим типы
numerics <- sapply(simplier, is.numeric)
simplier[, !numerics & names(simplier) !="pacient"] <- lapply(simplier[, !numerics & names(simplier) !="pacient"], as.factor)
```

```{r}
# Почищенная 2я группа!
group2_for_analysis <- simplier

```


### Переменные из группы 3:

```{r include=FALSE}

# Переменные группы 3:

group3 <- df_meta %>% filter(Analysis_group == 3) %>% 
                      select(cleaned_names) %>% pull()

df3 <- df %>% select(all_of(group3), pacient) 


# приводим переменные к нужному формату:
cols_to_fix <- c("fakticeskaa_massa_pred_tkm_epikriz", "cummarnaa_doza_razdelit_na_massu_tela_fakticeskuu_ili_plosad_tela_fakticeskuu",
                 "nc_ptkm_pdi", "cd34_kg_x10_ptkm_pdi")

df3 <- df3 %>%
  mutate(across(all_of(cols_to_fix), ~as.numeric(gsub(",", ".", .))))

# приведем к общим единицам измерения и переведем в числовой формат переменную cd3_kg_ptkm_pdi (c 10^7 на 10^6 клеток):

df3$cd3_kg_ptkm_pdi[(df3$cd3_kg_ptkm_pdi == "5,0х10*6")] <- "0,5х10*7"

convert_to_numeric <- function(x) {
  if (is.na(x)) {
    return(NA)
  }
  x <- gsub(",", ".", x)
  x <- gsub("x10\\*\\*([0-9]+)", "e\\1", x)
  x <- gsub("x10\\*([0-9]+)", "e\\1", x)
  parse_number(x)
}

df3 <- df3 %>% 
  mutate(cd3_kg_ptkm_pdi = sapply(cd3_kg_ptkm_pdi, convert_to_numeric))  

df3 <- df3 %>% mutate(cd3_kg_ptkm_pdi = cd3_kg_ptkm_pdi*10)

# Исключаем из анализа переменные с недостаточным числом значений (atg_pred_tk_me - "да" - только у одного пациента, можно описать текстом, переменная lucevaia_terapia - у 3 пациентов):

df3 <- df3 %>% select(!c(atg_pred_tk_me, lucevaa_terapia_skol_ko_grej_pred_tk_me))
```

```{r}
# Решено пациента с не проводившейся предТКЭ терапией отнести в группу анализа с немиелоаблативной терпией

df3 <- df3 %>% 
  mutate( rezim_kondicionirovania_pred_tk_me = if_else(rezim_kondicionirovania_pred_tk_me == "не проводится (BOOST)", "немиелоаблативный", rezim_kondicionirovania_pred_tk_me))
```

```{r echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
# Приведение схем профилактики РТПХ к одному виду

df3 <- df3 %>%
  mutate(preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me = 
           case_when(
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "Сиролимус, Такролимус, Циклофосфан" ~ "Циклофосфан, Такролимус, Сиролимус",
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "Циклофосфан, Такролимус, Сиролимус, " ~ "Циклофосфан, Такролимус, Сиролимус",
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "Сиролимус, Циклофосфан, MMF" ~ "Циклофосфан, Сиролимус, MMF",
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "Такролимус, MMF, Циклофосфан" ~ "Циклофосфан, Такролимус, MMF",
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "Такролимус, MMF, Циклофосфан, Бендамустин" ~ "Циклофосфан, Бендамустин, Такролимус, MMF",
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "Такролимус, Циклофосфан, MMF" ~ "Циклофосфан, Такролимус, MMF",
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "Сиролимус, MMF, Циклофосфан" ~ "Циклофосфан, Сиролимус, MMF",
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "Сиролимус, Селп-септ, Циклофосфан" ~ "Циклофосфан, Сиролимус, MMF",
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "Сиролимус, Циклофосфан" ~ "Циклофосфан, Сиролимус",
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "циклофосфан, Такролимус, MMF" ~ "Циклофосфан, Такролимус, MMF",
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "Циклофосфан, MMF, Такролимус" ~ "Циклофосфан, Такролимус, MMF",
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "Циклофосфан, Бендамустин, MMF, Такролимус" ~ "Циклофосфан, Бендамустин, Такролимус, MMF",
             preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me == "Циклофосфан, Такролимус, Селл-Септ" ~ "Циклофосфан, Такролимус, MMF",
             TRUE ~ preparaty_profilaktiki_rtph_libo_ne_provodilis_pred_tk_me
           ))
```



```{r}
# Приведение значений переменной моноклональных АТ к одному виду

df3 <- df3 %>%
  mutate(
    monoklonal_nye_antitela_nazvania_preparatov_pred_tk_me = 
      monoklonal_nye_antitela_nazvania_preparatov_pred_tk_me %>%
      str_replace("Bridge-терапия", "") %>%
      str_replace_all("\\s+", " ") %>%
      str_to_title()) 

df3 <- df3 %>% mutate( 
        monoklonal_nye_antitela_nazvania_preparatov_pred_tk_me = case_when(
        monoklonal_nye_antitela_nazvania_preparatov_pred_tk_me == "Руксолитиниб, Руксолитиниб" ~ "Руксолитиниб", 
       str_detect(`monoklonal_nye_antitela_nazvania_preparatov_pred_tk_me`, "Инотузумаб озогамицин") ~ "Инотузумаб, Озогамицин",
      str_detect(`monoklonal_nye_antitela_nazvania_preparatov_pred_tk_me`, "Гемтузумаб озогамицин") ~ "Гемтузумаб, Озогамицин",
        str_detect(`monoklonal_nye_antitela_nazvania_preparatov_pred_tk_me`, "Брентуксимаб Ниволумаб") ~ "Брентуксимаб, Ниволумаб",
      str_detect(`monoklonal_nye_antitela_nazvania_preparatov_pred_tk_me`, "Мидостаурином") ~ "Мидостаурин",
        TRUE ~ `monoklonal_nye_antitela_nazvania_preparatov_pred_tk_me`
  ))

# Значения колонок monoklonal_nye_antitela_pred_tk_me в некоторых случаях противоречат друг другу, в случае, если есть названия препаратов инотузумаб, блинатумомаб, брентуксимаб, ниволумаб, гемтузумаб, то в столбце monoklonal_nye_antitela_pred_tk_me должно быть "да", в остальных случаях - "нет".

df3 <- df3 %>% mutate(monoklonal_nye_antitela_pred_tk_me = case_when(str_detect(monoklonal_nye_antitela_nazvania_preparatov_pred_tk_me, 
               "Инотузумаб|Блинатумомаб|Брентуксимаб|Ниволумаб|Гемтузумаб") ~ "да",
    TRUE ~ "нет"
))
```

```{r include=FALSE}
# Режимы кондиционирования:

df %>% filter(`rezim_kondicionirovania_pred_tk_me` == "не проводится (BOOST)")

df %>% filter(`atg_pred_tk_me` == "да")

df3 <- df3 %>% mutate(shema_rk_pred_tk_me = case_when(
  shema_rk_pred_tk_me	== "#NAME?" ~ "FluBu",
  shema_rk_pred_tk_me	== "Bu + benda + Flu" ~ "FluBuBenda",
  shema_rk_pred_tk_me	== "Bu + Flu" ~ "FluBu",
  shema_rk_pred_tk_me	== "Flu + Bu" ~ "FluBu",
  shema_rk_pred_tk_me	== "Bu12 + Flu+ruxo" ~ "FluBuRuxo",
  shema_rk_pred_tk_me	== "Bu10 + Flu + Mel" ~ "FluBuMel",
  shema_rk_pred_tk_me	== "Flu + benda" ~ "FluBenda",
  shema_rk_pred_tk_me	== "Flu + Bu + benda" ~ "FluBuBenda",
  shema_rk_pred_tk_me	== "Flu + Bu + Mel" ~ "FluBuMel",
  shema_rk_pred_tk_me	== "Flu + Bu 12" ~ "FluBu",
  shema_rk_pred_tk_me == "Flu + Bu(10)" ~ "FluBu",
  shema_rk_pred_tk_me	== "Flu + Bu+Ruxo" ~ "FluBuRuxo",
  shema_rk_pred_tk_me	== "Flu + Bu10" ~ "FluBu",
  shema_rk_pred_tk_me	== "Flu + Bu14" ~ "FluBu",
  shema_rk_pred_tk_me	== "Flu + Bu8" ~ "FluBu",
  shema_rk_pred_tk_me	== "Flu + Cy" ~ "FluCy",
  shema_rk_pred_tk_me	== "Flu + Mel" ~ "FluMel",
  shema_rk_pred_tk_me	== "Flu + Treo" ~ "FluTreo",
  shema_rk_pred_tk_me == "FluBu10" ~ "FluBu",
  shema_rk_pred_tk_me == "FluBu8" ~ "FluBu",
  shema_rk_pred_tk_me == "FluBu12" ~ "FluBu",
  shema_rk_pred_tk_me == "FluBu14" ~ "FluBu",
  shema_rk_pred_tk_me	== "Mel + Flu" ~ "FluMel", 
  shema_rk_pred_tk_me	== "Treo + Flu" ~ "FluTreo", 
  TRUE ~ shema_rk_pred_tk_me
))
```

```{r, include=FALSE}
# Выделим в отдельные группы пациентов, получающих Треосульфан и Бусульфан, создадим переменные cummarnaa_doza_treosulfana, cummarnaa_doza_treosulfana_na_plosad_tela_fakticeskuu:

df3 <- df3 %>%
  mutate(
    cummarnaa_doza_treosulfana = ifelse(
      str_detect(preparaty_rezima_kondicionirovania_pred_tk_me, "Треосульфан"),
      cummarnaa_doza_busul_fana,
      NA
    ),
    cummarnaa_doza_busul_fana = ifelse(
      str_detect(preparaty_rezima_kondicionirovania_pred_tk_me, "Треосульфан"),
      0,
      cummarnaa_doza_busul_fana
    ),
    cummarnaa_doza_treosulfana_na_plosad_tela_fakticeskuu = ifelse(
      str_detect(preparaty_rezima_kondicionirovania_pred_tk_me, "Треосульфан"), cummarnaa_doza_razdelit_na_massu_tela_fakticeskuu_ili_plosad_tela_fakticeskuu, 
      NA
    ),
    cummarnaa_doza_razdelit_na_massu_tela_fakticeskuu_ili_plosad_tela_fakticeskuu = ifelse(
      str_detect(preparaty_rezima_kondicionirovania_pred_tk_me, "Треосульфан"),
      0,
      cummarnaa_doza_razdelit_na_massu_tela_fakticeskuu_ili_plosad_tela_fakticeskuu
    ),
    cummarnaa_doza_busulfana_razdelit_na_massu_tela = cummarnaa_doza_razdelit_na_massu_tela_fakticeskuu_ili_plosad_tela_fakticeskuu
  ) %>%
  select(!c(cummarnaa_doza_razdelit_na_massu_tela_fakticeskuu_ili_plosad_tela_fakticeskuu, cummarnaa_doza_treosulfana, cummarnaa_doza_treosulfana_na_plosad_tela_fakticeskuu))
  
         
# Переменные cummarnaa_doza_treosulfana, cummarnaa_doza_treosulfana_na_plosad_tela_fakticeskuu не включаем в анализ, так как данный препарат получали только 2 пациента

# Если доза Бусульфана = 0, заменим на NA:

df3 <- df3 %>%
  mutate(cummarnaa_doza_busul_fana = ifelse(cummarnaa_doza_busul_fana == 0, NA, cummarnaa_doza_busul_fana),
         cummarnaa_doza_busulfana_razdelit_na_massu_tela = ifelse(cummarnaa_doza_busulfana_razdelit_na_massu_tela == 0,
                                                                  NA, cummarnaa_doza_busulfana_razdelit_na_massu_tela))
```

```{r}
# В переменной summarnaa_doza_pred_tk_me для пациента, которому не проводилась предТКМ терапия, указано значение ", ", заменим на NA:

df3 <- df3 %>% 
  mutate(summarnaa_doza_pred_tk_me = ifelse(summarnaa_doza_pred_tk_me == ", ", NA, summarnaa_doza_pred_tk_me))

# Удалим колонку о манипуляциях с трансплантатом, указать в описании, что всем с BM трансплантатом проводилось фракционирование

df3 <- df3 %>% select(!manipulacii_s_transplantatom_ptkm)
```


```{r}
# Перераспределение на группы по совместимости донора и реципиента: донор родств/неродств -> совместимость частичн/полная:
df3 <- df3 %>% mutate(vid_tkm_nastoasej_ptkm_pred_tk_me_pditkm = case_when(
  str_detect(vid_tkm_nastoasej_ptkm_pred_tk_me_pditkm, "неродственная") ~ "неродственная", TRUE ~ "родственная")) %>%
  mutate(sovmestimost_donora_recipienta_ptkm_pred_tk_me = case_when(
  str_detect(sovmestimost_donora_recipienta_ptkm_pred_tk_me, "частично") ~ "частично совместимы", TRUE ~ "полностью совместимы"))
```

```{r}
# Создадим отдельный датасет на случай необходимости анализа отдельных препаратов из схем режима кондиционирования и удалим из основного датасета колонки preparaty_rezima_kondicionirovania_pred_tk_me, summarnaa_doza_pred_tk_me


# Таблица по дозам и количеству доз препаратов режима кондиционирования

conditioning <- tibble(patient = df3$pacient,
                       schema = df3$shema_rk_pred_tk_me,
                       drug = df3$preparaty_rezima_kondicionirovania_pred_tk_me,
                       dose = df3$summarnaa_doza_pred_tk_me,
                       bu_dose = df3$cummarnaa_doza_busul_fana)


 conditioning <- conditioning %>% 
  pivot_longer(
    cols = c(drug, dose),
    names_to = "variable",
    values_to = "value",
    values_drop_na = TRUE
  ) %>%
  separate_rows(value, sep = "[,;]\\s*") %>%
  pivot_wider(names_from = variable, values_from = value) %>% unnest(cols = c(drug, dose))

 
 conditioning <- conditioning %>%
  group_by(patient) %>%
  mutate(drug_number = row_number()) %>% select(patient, schema, drug_number, drug, dose, bu_dose) %>% mutate(dose = as.numeric(dose)) 
 
 # У пациента 51 терапия не проводилась, у пациента 60 - 2 препарата, внесем корректировки в датасет:
 
 conditioning <- conditioning %>% filter(!(patient == "Patient51")) %>% filter(!(patient == "Patient60" & drug_number == 3))
 
 conditioning <- conditioning %>% mutate(drug = case_when(
  drug	== "Флударабин" ~ "Флюдарабин",
  TRUE ~ drug))

 
df3 <- df3 %>% select(!c(preparaty_rezima_kondicionirovania_pred_tk_me, summarnaa_doza_pred_tk_me))
```


### Переменные из группы 4:


```{r message=FALSE, warning=FALSE}
outcome_var <- df_meta %>%
  filter(Analysis_group == 4) %>%
  pull(cleaned_names)

trans_outcomes <- df %>%
  select(pacient, all_of(outcome_var)) #Датафрейм - все исходы

trans_outcomes_wrk <- trans_outcomes %>%
  select(pacient, ly30, ly60, ly100, neu30, neu60, neu100, plt30, plt60, plt100,
         os2, os2time, rel2, rel2time, compete2, compete2time, efs2, efs2time,
         a_gvhd24, a_gvhd24time, a_gvhd34, a_gvhd34time, c_gvhd, c_gvh_dtime,
         data_tkm_iz_protokola_ptkm_pdi,
         vysevy_iz_cvk_v_pervye_30_nej_posle_tkm,
         vosstanovlenie_lejkocity_data_tpp_100_dn,
         vosstanovlenie_nejtrofily_data_tpp_100_dn,
         vosstanovlenie_tr20_data_tpp_100_dn,
         vosstanovlenie_tr50_data_tpp_100_dn,
         wbc_2, neu, plt20, plt50, ottorzenie_tpp_100dn,
         ortph_da_net_tpp_100dn, agvhd_stage, agvhd_date,
         data_poslednego_kontakta,
         byl_li_zaregistrirovan_recidiv_progressia_osnovnogo_zabolevania_posle_tkm_1god,
         data_recidiva_1god, zaregistrirovana_hroniceskaa_rtph_na_d_365_1god,
         data_nacala_1god, forma_1god,
         contains('stepen_1god'),
         contains('proavlen'),
         summarnaa_stepen_tazesti_hrtph_1god) #Рабочий датафрейм с исходами (только желтые колонки)

rm(outcome_var)
```

```{r}
# Корректируем типы данных
trans_outcomes_wrk <- trans_outcomes_wrk %>%
  mutate_at(c('ly30', 'ly60', 'ly100', 'neu30', 'neu60', 'neu100'),
            str_replace,
            pattern = ",",
            replacement = ".") %>%
  mutate_at(c('ly30', 'ly60', 'ly100', 'neu30', 'neu60', 'neu100'), as.numeric) %>%
  mutate_at(c('os2', 'rel2', 'compete2', 'efs2', 'a_gvhd24', 'a_gvhd34', 'c_gvhd', 'ortph_da_net_tpp_100dn', 'agvhd_stage', 'byl_li_zaregistrirovan_recidiv_progressia_osnovnogo_zabolevania_posle_tkm_1god', 'zaregistrirovana_hroniceskaa_rtph_na_d_365_1god', 'drugie_proavlenia_hrtph_1god'), as.factor) %>%
  mutate_at(c('data_tkm_iz_protokola_ptkm_pdi', 'vosstanovlenie_lejkocity_data_tpp_100_dn', 'vosstanovlenie_nejtrofily_data_tpp_100_dn', 'vosstanovlenie_tr20_data_tpp_100_dn', 'vosstanovlenie_tr50_data_tpp_100_dn', 'agvhd_date', 'data_poslednego_kontakta', 'data_recidiva_1god', 'data_nacala_1god'), ~ format(as.Date(., format = "%Y-%m-%d"), "%d.%m.%Y")) %>%
  mutate(across(contains('stepen'), ~ factor(.)))
```

```{r}
# Работаем с текстовыми колонками
trans_outcomes_wrk <- trans_outcomes_wrk %>%
  mutate(cvk_not_sterile = as.factor(ifelse(str_detect(vysevy_iz_cvk_v_pervye_30_nej_posle_tkm, 'не стерильно'), 1, 0)),
         cvk_vysev_type = as.factor(str_remove(vysevy_iz_cvk_v_pervye_30_nej_posle_tkm, ": не стерильно"))) # Разбили столбец с высевами

trans_outcomes_wrk <- trans_outcomes_wrk %>%
  mutate(ottorzenie_tpp_100dn = as.factor(ottorzenie_tpp_100dn))
```



### Объединение в один датасет


```{r}
list_of_datasets <- list(Donor, group2_for_analysis, df3, trans_outcomes_wrk)

# Объединение датасетов по колонке "pacient" с использованием функции Reduce
main_df <- Reduce(function(x, y) merge(x, y, by = "pacient", all = TRUE), list_of_datasets)

```


### Добавление лэйблов


```{r}
describtion <- data.frame(names = names(main_df)) %>%  
  left_join(., df_meta %>% select(cleaned_names, Describtion), 
            by = c("names" = "cleaned_names")) %>% mutate(Describtion = case_when(
              names == "cummarnaa_doza_busulfana_razdelit_na_massu_tela" ~ "Суммарная доза Бусульфана разделить на массу тела", 
              names == "male" ~ "Пол (М - 1, Ж - 0)",
              names == "relative" ~ "Родственный донор (Да - 1, Нет - 0)",
              names == "intratekalnoe_vvedenie" ~ "Интретекатльное введение",
              names == "cvk_not_sterile" ~ "Высевы из ЦВК + (Да - 1, Нет - NA)",	
              names == "cvk_vysev_type" ~ "Высевы из ЦВК: заключение",
              TRUE ~ Describtion
            ))
   

var_labels <- setNames(as.list(describtion$Describtion), describtion$names)
  main_df <- main_df %>%
    set_variable_labels(.labels = var_labels, .strict = FALSE)
  var_label(main_df)
  
main_df <- main_df %>% mutate(
    pacient = gsub("Patient", "", pacient))

```

